---
- name: update file with information
  hosts: all
  become: yes

  tasks:
    - name: Update file with Information
      ansible.builtin.lineinfile:
        path: /tmp/hostfile.txt
        line: "This hostname is {{ ansible_hostname }}"
        state: present
        create: yes
      register: hostname

    - name: write hostname to file
      copy:
        content: "{{hostname.stdout}}"
        dest: "/root/tests/hostfile.txt"
